const map = {
  "ot": { abr: "OT", ful: "Old Testament" },
  "gen": { abr: "Gen", ful: "Genesis" },
  "ex": { abr: "Ex", ful: "Exodus" },
  "lev": { abr: "Lev", ful: "Leviticus" },
  "num": { abr: "Num", ful: "Numbers" },
  "deut": { abr: "Deut", ful: "Deuteronomy" },
  "josh": { abr: "Josh", ful: "Joshua" },
  "judg": { abr: "Judg", ful: "Judges" },
  "ruth": { abr: "Ruth", ful: "Ruth" },
  "1-sam": { abr: "1 Sam", ful: "1 Samuel" },
  "2-sam": { abr: "2 Sam", ful: "2 Samuel" },
  "1-kgs": { abr: "1 Kgs", ful: "1 Kings" },
  "2-kgs": { abr: "2 Kgs", ful: "2 Kings" },
  "1-chr": { abr: "1 Chr", ful: "1 Chronicles" },
  "2-chr": { abr: "2 Chr", ful: "2 Chronicles" },
  "ezra": { abr: "Ezra", ful: "Ezra" },
  "neh": { abr: "Neh", ful: "Nehemiah" },
  "esth": { abr: "Esth", ful: "Esther" },
  "job": { abr: "Job", ful: "Job" },
  "ps": { abr: "Ps", ful: "Psalms" },
  "prov": { abr: "Prov", ful: "Proverbs" },
  "eccl": { abr: "Eccl", ful: "Ecclesiastes" },
  "song": { abr: "Song", ful: "Songs of Solomon" },
  "isa": { abr: "Isa", ful: "Isaiah" },
  "jer": { abr: "Jer", ful: "Jeremiah" },
  "lam": { abr: "Lam", ful: "Lamentations" },
  "ezek": { abr: "Ezek", ful: "Ezekiel" },
  "dan": { abr: "Dan", ful: "Daniel" },
  "hosea": { abr: "Hosea", ful: "Hosea" },
  "joel": { abr: "Joel", ful: "Joel" },
  "amos": { abr: "Amos", ful: "Amos" },
  "obad": { abr: "Obad", ful: "Obadiah" },
  "jonah": { abr: "Jonah", ful: "Jonah" },
  "micah": { abr: "Micah", ful: "Micah" },
  "nahum": { abr: "Nahum", ful: "Nahum" },
  "hab": { abr: "Hab", ful: "Habakkuk" },
  "zeph": { abr: "Zeph", ful: "Zephaniah" },
  "hag": { abr: "Hag", ful: "Haggai" },
  "zech": { abr: "Zech", ful: "Zechariah" },
  "mal": { abr: "Mal", ful: "Malachi" },
  "nt": { abr: "NT", ful: "New Testament" },
  "matt": { abr: "Matt", ful: "Matthew" },
  "mark": { abr: "Mark", ful: "Mark" },
  "luke": { abr: "Luke", ful: "Luke" },
  "john": { abr: "John", ful: "John" },
  "acts": { abr: "Acts", ful: "Acts" },
  "rom": { abr: "Rom", ful: "Romans" },
  "1-cor": { abr: "1 Cor", ful: "1 Corinthians" },
  "2-cor": { abr: "2 Cor", ful: "2 Corinthians" },
  "gal": { abr: "Gal", ful: "Galations" },
  "eph": { abr: "Eph", ful: "Ephesians" },
  "philip": { abr: "Philip", ful: "Philippians" },
  "col": { abr: "Col", ful: "Colossians" },
  "1-thes": { abr: "1 Thes", ful: "1 Thessalonians" },
  "2-thes": { abr: "2 Thes", ful: "2 Thessalonians" },
  "1-tim": { abr: "1 Tim", ful: "1 Timothy" },
  "2-tim": { abr: "2 Tim", ful: "2 Timothy" },
  "titus": { abr: "Titus", ful: "Titus" },
  "philem": { abr: "Philem", ful: "Philemon" },
  "heb": { abr: "Heb", ful: "Hebrews" },
  "james": { abr: "James", ful: "James" },
  "1-pet": { abr: "1 Pe", ful: "1 Peter" },
  "2-pet": { abr: "2 Pe", ful: "2 Peter" },
  "1-jn": { abr: "1 Jn", ful: "1 John" },
  "2-jn": { abr: "2 Jn", ful: "2 John" },
  "3-jn": { abr: "3 Jn", ful: "3 John" },
  "jude": { abr: "Jude", ful: "Jude" },
  "rev": { abr: "Rev", ful: "Revelation" },
  "bofm": { abr: "B of M", ful: "Book of Mormon" },
  "1-ne": { abr: "1 Ne", ful: "1 Nephi" },
  "2-ne": { abr: "2 Ne", ful: "2 Nephi" },
  "jacob": { abr: "Jacob", ful: "Jacob" },
  "enos": { abr: "Enos", ful: "Enos" },
  "jarom": { abr: "Jarom", ful: "Jarom" },
  "omni": { abr: "Omni", ful: "Omni" },
  "w-of-m": { abr: "W of M", ful: "Words of Mormon" },
  "mosiah": { abr: "Msh", ful: "Mosiah" },
  "alma": { abr: "Alma", ful: "Alma" },
  "hel": { abr: "Hel", ful: "Helaman" },
  "3-ne": { abr: "3 Ne", ful: "3 Nephi" },
  "4-ne": { abr: "4 Ne", ful: "4 Nephi" },
  "morm": { abr: "Morm", ful: "Mormon" },
  "ether": { abr: "Ether", ful: "Ether" },
  "moro": { abr: "Moro", ful: "Moroni" },
  "dc-testament": { abr: "D&C", ful: "Doctrine & Covenants" },
  "dc": { abr: "D&C", ful: "Doctrine & Covenants" },
  "pgp": { abr: "P of GP", ful: "Pearl of Great Price" },
  "moses": { abr: "Moses", ful: "Moses" },
  "abr": { abr: "Abr", ful: "Abraham" },
  "js-m": { abr: "JS-M", ful: "Joseph Smith-Matthew" },
  "js-h": { abr: "JS-H", ful: "Joseph Smith-History" },
  "a-of-f": { abr: "A of F", ful: "Articles of Faith" }
}

module.exports = function(prop) {
  return map[prop];
}
